name: (v2) Export Evapotranspiration

on:
    workflow_dispatch:
    schedule:
        - cron: '0 20 * * *'

jobs:
    v2-export-evapotranspiration:
        uses: ./.github/workflows/export.yaml
        with:
            data-type: 'v2/evapotranspiration'
